config/routes.rb
Rails.application.routes.draw do
  get 'todos',to:'todos#index',as:'todos'
  get 'todos/new'
  post 'todos', to:'todos#create'
  get 'todos/list',to:'todos#list',as:'list'
  get 'todos/:id',to:'todos#show' ,as:'todo'
  get 'todos/:id/edit',to:'todos#edit',as:'edit'
  patch 'todos/:id',to:'todos#update'
  delete 'todos/:id',to:'todos#destroy'
  get 'todos/:id/completed', to:'todos#completed',as:'completed'
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only:[:show,:edit,:update,:destroy,:completed,]
  def index
    @todos=Todo.all
  end
  def new
    @todo=Todo.new
  end
  def create
    todo= Todo.create(todo_params)
    todo.completed=false
    todo.save
    redirect_to todos_path
  end
  def show;end
  def edit;end
  def update
  @todo.update(todo_params)
  redirect_to todo_path
  end
  def destroy
    @todo.destroy()
      redirect_to todos_path
  end
  def completed
    @todo.completed=true
    @todo.save
    redirect_to todos_path
  end
  def list
    @todos_list=Todo.where(completed:true)
    @todos_list_false=Todo.where(completed:false)
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
  def set_todo
    @todo=Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"><%=image_tag "ghost.png",class:"img-fluid" , alt:"una imagen", width:"30"%> <%=link_to "Nuevo ToDo", todos_new_path ,class:"btn btn-info" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
         <ul class= "navbar-nav">
           <li class="nav-item <%= 'active' if action_name == 'todos' %>" >
          <%=link_to "todos",todos_path,class:"nav-item nav-link"%>
          </li>
          <li class="nav-item <%='active' if action_name == 'list' %>" >
          <%=link_to "list",list_path,class:"nav-item nav-link"%>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/views/todos/edit.html.erb
<h1>Edit</h1>
<br>
<div class="card bg-info container ">

<br>
<%=form_with(model: @todo, local:true) do |t|%>

<%=t.label :description ,class:'col-sm-2'%>
<%=t.text_field :description,class:'col-sm-4'%>
<%=t.submit 'Editar',class:'btn btn-warning col-sm-1'%>
<%end%>
<br>
</div>
<br>
<%=link_to '<<<Back', todos_path,class:'btn btn-danger ws'%>

app/views/todos/index.html.erb
<h1>ToDo</h1>

<% @todos.each do |todo| %>
<div class="card text-white bg-info container">
  <p class=''><%="#{todo.description}"%></p>
  <div class="row-1">
    <%= link_to 'Ver', todo,class:"btn text-white btn-success col-1 "%>
    <%= link_to 'Editar',edit_path(todo),class:"btn  text-white btn-warning col-sm-1 "%>
    <%= link_to 'Eliminar', todo, method: :delete , data:{confirm:'seguro que quieres borrar!!'},class:"btn text-white btn-danger col-sm-1"%>
    <%= link_to 'completado',completed_path(todo) ,class:"btn text-white btn-dark col-sm-3"%>
  </div>
<br>
</div>
<br>
<%end%>

app/views/todos/list.html.erb
<h1>List</h1>

<div class=" row">


<div class="card bg-danger col">
<h2>No Completado</h2>
<% @todos_list_false.each do |todo| %>
<p><%="#{todo.description}"%></p>
<%end%>
</div>
<div class="card bg-success col">
<h2>Completado</h2>
<% @todos_list.each do |todo| %>
<p><%="#{todo.description}"%></p>
<%end%>
</div>

</div>

app/views/todos/new.html.erb
<h1>New</h1>
<br>
<%=form_with(model: @todo, local:true) do |t|%>

<%=t.label :description ,class:'col-sm-1'%>
<%=t.text_field :description,class:'col-sm-1'%>
<%=t.submit 'Crear',class:'btn btn-info col-sm-1'%>
<%end%>

<br>
<%=link_to '<<<Back', todos_path, class:'btn btn-danger col-sm-1'%>

app/views/todos/show.html.erb
<h1>show</h1>
<div class="card container bg-info">


<% if @todo.completed == true  %>
<% complete= "completado"%>
<% else %>
<% complete= "no completado"%>
<% end %>
<h3><%= "#{@todo.description}"%></h3>
<% if @todo.completed == true%>
<h3 class="h33"><%="#{complete}"%></h3>
<% else %>
<h3 class="h34"><%="#{complete}"%></h3>
<% end %> 
</div>
<%=link_to "<<<Atras",todos_path,class:'btn btn-danger' %>